### ISSUE TITLE
Wurstauction demo example

### ISSUE THREAD

**Issue by nenadjaja** [graphprotocol/wurstauction#1]
This project contains 3 parts: 
1. Solidity: smart contracts for creating an auction for Bitsausage coin
2. Subgraph: for getting the auction data 
3. Dapp: UI for bidding

Work that needs to be done:
- [x] Finish UI for desktop and responsive https://github.com/graphprotocol/wurstauction/issues/2
- [x] Add a check for Metamask https://github.com/graphprotocol/wurstauction/issues/3
- [x] Add bidding logic and messaging: update the message when your bid is the highest and when not https://github.com/graphprotocol/wurstauction/issues/4
- [x] Write Truffle script to populate data https://github.com/graphprotocol/wurstauction/issues/5
- [ ] Connect the GraphQL endpoint https://github.com/graphprotocol/the-graph-website/issues/88
